changelog:
  exclude:
    labels:
      - ignore-for-release
      - github-actions
    authors:
      - octocat
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
        - feat
    - title: Bug fixes 🐛
      labels:
        - bug
        - fix
    - title: Other Changes 🔄
      labels:
        - "*"
