changelog:
  exclude:
    labels:
      - ignore-for-release
      - github-actions
    authors:
      - octocat
  categories:
    - title: Exciting New Features 🎉
      labels:
        - feature
    - title: Bug fixes 🐛
      labels:
        - bug
    - title: Dependencies 👒
      labels:
        - dependencies
    - title: Other Changes 🔄
      labels:
        - "*"
